name: "Tests"

on:
  push:
  schedule:
  - cron: "0 3 * * 5"
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: mlugg/setup-zig@v1
      - name: Formatting
        run: zig fmt --check src/*.zig
      - name: Tests
        run: zig build test
